name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install demo dependencies
        run: sudo apt-get install jq
      
      - uses: education/autograding@v1

      - name: Run demo
        run: ./system demo | jq --color-output
      
